---
name: mfa-authenticator
After:
  - #coresecurity
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\Security:
    properties:
      Authenticators:
        default: %$SilverStripe\MFA\Authenticator\MemberAuthenticator
---
name: mfa-memberextension
---
SilverStripe\Security\Member:
  extensions:
    mfaExtension: SilverStripe\MFA\Extension\MemberExtension
