---
name: MFAAuthenticator
After:
  - #coresecurity
---
SilverStripe\Security\Member:
  extensions:
    - Firesphere\BootstrapMFA\Extensions\MemberExtension
Firesphere\BootstrapMFA\Models\BackupCode:
  token_limit: 15
Firesphere\BootstrapMFA\Generators\CodeGenerator:
  length: 6
  type: mixed
  case: mixed
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Firesphere\BootstrapMFA\Extensions\SiteConfigExtension